language: node_js
node_js:
  - node 
services:
  - postgresql
addons:
  postgresql: '9.6' 
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "marvel-ous-test";' -U postgres
script:
  - npm test             # test the code
  - npm run build-client # make the bundle

before_deploy:
  - rm -rf node_modules 
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: marvel-ous
  api_key:
    secure: "s8RuJZHTtAXsvM7UdyE9cyczh4AS2jDU4TGoBHH7aKF8IElG2S3VA4nljA0oINrx4wWNUmMVckMHrowjY2SDzVASe2idcdfC615fBPwMvUpoU8dkR4aBKYvWSH0NJEjNkuZtBhycym1YXOGDMJgOTcSHL973pVxyOUoQIv+wUsjod1mUTZmM+lQyKOauWlsc67V5l77GZOQnuSW6b5jdEbQ5gColIEZnjijIvRZj1EIOe9p7cyCef7WfKsy6ee8Kk0LEPTi0Woeztw4+L+R836DXeHJFXNmQxvV7S1rvcYiExVM6lGKdtS/jvyuXlblUpqqtTtkXQBsB9gYb/kjqc0e93T/tQknwc5WoQOQ7UBlUGM3FNhWm4SL/R1JoXiG/28K7UpGYwwmSABekmVRdPaswt78OtEcjmM51wjYhwXi4ovsf+TXikobgb4lK92sKAiBoLSQd9raftdBkv+gH6SYTr5NIoFFviWYe/xU4wFjV+IRQ1WqHHWfyICikYINfTtBxjJ3NKCRMAjbKeekqIjClbR/Ify7b0RP42e9aXXyRZ3sLqB6dasSHLysVOcW1KEv6Hilh1y8adclbDB9B8rNO35HHAH5r33SQSkga9SbVJ7CLt5poLvORxiLHloAWnHNnHjBqQ+cuYv+vU5d4TYzeMGYHZKUwb5CyS3NMMjk="
